site_name: 'Тинькофф Инвестиции OpenApi'
docs_dir: docs
repo_url: https://github.com/TinkoffCreditSystems/invest-openapi
theme:
  name: material
  language: 'ru'
  palette:
    primary: black
    accent: yellow
  # custom_dir: swagger-iu/

nav:
- Начало работы: index.md
- Авторизация: auth.md
- Окружения: env.md
- "Протокол: rest": rest.md
- "Протокол: streaming": marketdata.md
- FAQ: faq.md
